tokenapp/urls.py
from django.urls import path
from tokenapp import views

app_name = 'tokenapp'

urlpatterns=[
    path('register/',views.register, name='register'),
    path('user_login/',views.user_login,name='user_login'),
]

tokenauth/urls.py
from django.contrib import admin
from django.urls import path,include
from tokenapp import views
from django.conf.urls.static import static 
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index'),
    path('tokenapp/',include('tokenapp.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('after_login/',views.after_login, name='after_login'),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tokenapp/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.user.username

tokenapp/forms.py
from django import forms
from django.contrib.auth.models import User
from tokenapp.models import *

class Userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

tokenapp/views.py
from django.shortcuts import render
from tokenapp.forms import Userform,UserProfileInfoForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from .models import UserProfileInfo
from .profile_pics import *

@login_required
def after_login(request):
    alldata = UserProfileInfo.objects.all()
    return render(request, 'after_login.html', {"alldata": alldata})

def index(request):
    return render(request, 'index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = Userform(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered=True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = Userform()
        profile_form = UserProfileInfoForm()

    return render(request, 'registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})


def user_login(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('after_login'))

            else:
                return HttpResponse("account not active")

        else:
            print("someone tried to login and failed")
            print("username:{} and password {}".format(username, password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request,'login.html',{})

tokenapp/templates/after_login.html
{% extends 'base.html' %}

{% block body_block %}

<h1>Welcome {{user.username}}</h1>
<div class="row">
    <div class="col-md-3">
        <div class="card card-body">
            <img src="{{user.userprofileinfo.profile_pic.url}}" style="width: 200px; height: 200px;">
        </div>
    </div>
</div>


{% endblock %}

tokenapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="navbar-brand" href="{% url 'index'%}">Django</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index'%}">Admin</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'tokenapp:register'%}">Register</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'tokenapp:user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>


    <div>
        {% block body_block %}
        {% endblock %}
    </div>
    
</body>
</html>

tokenapp/templates/index.html
{% extends "base.html" %}
{% load static %}


{% block body_block %}

<div class="jumbotron">
    <h1>django level 5</h1>
</div>
{% endblock %}

tokenapp/templates/login.html
{% extends 'base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please login</h1>
    <form action="{% url 'tokenapp:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">username:</label>
        <input type="text" name="username" placeholder="Enter username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">
    </form>

</div>

{% endblock %}

tokenapp/templates/registration.html
{% extends "base.html" %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>
            thank you for registering
        </h1>
    {% else %}
        <h1>register here!</h1>
        <h3>Fill out the form</h3>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{user_form.as_p}}
            {{profile_form.as_p}}
            <input type="submit" value="register">
        </form>

    {% endif %}
</div>

{% endblock %}